# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CmdLine@2
  inputs:
    script: |
      echo "Here we are going to fetch a cat fact"
      URL="https://cat-fact.herokuapp.com/facts/random"
      response=$(curl -s -w "%{http_code}" $URL)
      http_code=$(tail -n1 <<< "$response")  # get the last line
      content=$(sed '$ d' <<< "$response")   # get all but the last line which contains the status code
      echo "$http_code"
      echo "$content"
      echo "Cat fact fetched success"


- task: PowerShell@2
  inputs:
    filePath: './azureShellScript.ps1'